config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth'
  root "users#index"
  resources :users

  patch "/users/:id/check_gender", to: "users#check_gender", as: "check_gender"

  patch "/users/save_gender", to: "users#save_gender"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :last_request_and_gender

  def correct?
    is_correct
  end

  def admin?
    is_admin
  end

  private
  def last_request_and_gender
    full_name = self.full_name
    data = Dadata.check_gender(full_name)
    self.gender = data[:gender]
    self.last_request = data[:last_request]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :is_admin])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:index]

  # GET /users or /users.json
  def index
    @users = policy_scope(User)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def save_gender
    current_user.is_correct = true
    current_user.save
    redirect_to root_path, notice: "Gender correct!"
  end

  def check_gender
    @user = User.find(params[:id])
    data = Dadata.check_gender(@user.full_name)
    @user.gender = data[:gender]
    @user.last_request = data[:last_request]
    @user.save
    redirect_to root_path, notice: "Gender checked!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :full_name, :gender, :is_admin, :last_request)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GenderDeterminer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <%= link_to "Gender Determiner", root_path, class: "navbar-brand" %>
        <div class="d-flex">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to current_user.full_name, edit_user_registration_path, class: "nav-link active" %></li>
              <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link active" %></li>
            <% else %>
              <li class="nav-item"><%= link_to "Sign in", new_user_session_path, class: "nav-link active" %></li>
              <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: "nav-link active" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="p-3 mb-2 bg-success text-white">
        <%= notice %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="p-3 mb-2 bg-danger text-white">
        <%= alert %>
      </div>
    <% end %>

    <div class="container">
      <div class="row mt-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="col">
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :full_name, class: "form-label" %>
      <%= form.text_field :full_name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :gender, class: "form-label" %>
      <%= form.text_field :gender, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :is_admin, class: "form-check-label" %>
      <%= form.check_box :is_admin, class: "form-check-input" %>
    </div>

    <div class="mb-3">
      <%#= form.label :last_request %>
      <%#= form.datetime_select :last_request %>
    </div>

    <div class="mb-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="col">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.slim
.col
  table.table.table-striped
    thead
      tr
        th Full name
        th Gender
        th Is admin
        th Last request
        th colspan="4"
    tbody
      - @users.each do |user|
        tr
          td =user.full_name
          td =user.gender
          td =user.is_admin
          td =user.last_request.in_time_zone('Europe/Moscow').to_formatted_s(:short)
          td =link_to 'Show', user
          td =link_to 'Edit', edit_user_path(user)
          td =link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
          td =link_to "Check", check_gender_path(user), method: :patch

  - unless current_user.correct?
    div
      h4 You gender: #{current_user.gender}. Correct?
      =link_to "Correct", users_save_gender_path, method: :patch, data: { confirm: 'Are you sure? '}
      =link_to "Incorrect", edit_user_path(current_user)

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="co">
  <p>
    <strong>Full name:</strong>
    <%= @user.full_name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @user.gender %>
  </p>

  <p>
    <strong>Is admin:</strong>
    <%= @user.is_admin %>
  </p>

  <p>
    <strong>Last request:</strong>
    <%= @user.last_request %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>